### ISSUE TITLE
使用する単語をREAD.MEにかきました

### ISSUE THREAD

**Issue by TakatamaTsubasa** [temochiz-lab/takatama-2022#5]
タイトルの通りです。７/４、沼倉さんのプログラムの様子を見たいと思います！よろしくお願いいたします。

**Comment by temochiz-lab** [comment]
了解しました。
沼倉さんのプログラムは
https://github.com/temochiz-lab/numakura-2022
からダウンロードして確認できます。

内容確認したのでチケットはクローズしておきます。
